data = [{'name': 'ski', 'brands': ['rosignol', 'nordica', 'head']},
        {'name': 'table-tennis', 'brands': ['pongori', 'stiga', 'joola']},
        {'name': 'climbing', 'brands': ['simond', 'sparta', 'petzl']},
        {'name': 'running', 'brands': ['saucony', 'adidas', 'nike']}]

products = {
    'rosignol': [
        {'name': 'rtx-2000',
         'price': 1500,
         'season': '\'17 summer',
         'color': 'red'},
        {'name': 'rtx-1800',
         'price': 2800,
         'season': '\'17 summer',
         'color': 'yellow'},
        {'name': 'gtx-2500',
         'price': 19000,
         'season': '\'17 summer',
         'color': 'black'}],
    'nordica': [
        {'name': 'nimbus-2000',
         'price': 7500,
         'season': '\'17 summer',
         'color': 'violet'},
        {'name': '1329sx',
         'price': 8200,
         'season': '\'17 summer',
         'color': 'indigo'},
        {'name': '200mx',
         'price': 13000,
         'season': '\'17 summer',
         'color': 'orange'}],
    'head': [
        {'name': 'odin',
         'price': 15000,
         'season': '\'21 summer',
         'color': 'grey'},
        {'name': 'baldur',
         'price': 82000,
         'season': '\'21 summer',
         'color': 'white'},
        {'name': 'freya',
         'price': 47000,
         'season': '\'21 summer',
         'color': 'silver'}],
    'pongori': [],
    'stiga': [],
    'joola': [],
    'simond': [],
    'sparta': [],
    'petzl': [],
    'saucony': [],
    'adidas': [],
    'nike': []
}
